export enum NODE_TYPE {
    OPENING = "OPENING_NODE",
    CLOSING = "CLOSING_NODE",
    SELF_CLOSING = "SELF_CLOSING_NODE",
    META = "META_NODE",
    SCRIPT = "SCRIPT_NODE",
    STYLE = "STYLE_NODE",
    COMMENT = "COMMENT_NODE",
    TEXT = "TEXT_NODE"
}
