export enum STATE {
    NONE = "NONE",

    TEXT_NODE = "TEXT_NODE",

    NODE_START = "NODE_START",

    CLOSING_NODE = "CLOSING_NODE",
    META_NODE = "META_NODE",
    COMMENT_NODE = "COMMENT_NODE",
    COMMENT_NODE_BODY = "COMMENT_NODE_BODY",
    COMMENT_NODE_END_1 = "COMMENT_NODE_END_1",
    COMMENT_NODE_END_2 = "COMMENT_NODE_END_2",

    NODE_START_SCRIPT_OR_STYLE_1 = "NODE_START_SCRIPT_OR_STYLE_1",

    NODE_START_SCRIPT_2 = "NODE_START_SCRIPT_2",
    NODE_START_SCRIPT_3 = "NODE_START_SCRIPT_3",
    NODE_START_SCRIPT_4 = "NODE_START_SCRIPT_4",
    NODE_START_SCRIPT_5 = "NODE_START_SCRIPT_5",
    NODE_START_SCRIPT_6 = "NODE_START_SCRIPT_6",

    NODE_START_STYLE_2 = "NODE_START_STYLE_2",
    NODE_START_STYLE_3 = "NODE_START_STYLE_3",
    NODE_START_STYLE_4 = "NODE_START_STYLE_4",
    NODE_START_STYLE_5 = "NODE_START_STYLE_5",


    NODE_SCRIPT_BODY = "NODE_SCRIPT_BODY",

    NODE_STYLE_BODY = "NODE_STYLE_BODY",


    NODE_SCRIPT_ATTR_NAME = "NODE_SCRIPT_ATTR_NAME",
    NODE_SCRIPT_ATTR_VALUE_START = "NODE_SCRIPT_ATTR_VALUE_START",
    NODE_SCRIPT_ATTR_VALUE_BODY_DOUBLE_QUOTATION = "NODE_SCRIPT_ATTR_VALUE_BODY_DOUBLE_QUOTATION",
    NODE_SCRIPT_ATTR_VALUE_BODY_SINGLE_QUOTATION = "NODE_SCRIPT_ATTR_VALUE_BODY_SINGLE_QUOTATION",

    NODE_STYLE_ATTR_NAME = "NODE_STYLE_ATTR_NAME",
    NODE_STYLE_ATTR_VALUE_START = "NODE_STYLE_ATTR_VALUE_START",
    NODE_STYLE_ATTR_VALUE_BODY_DOUBLE_QUOTATION = "NODE_STYLE_ATTR_VALUE_BODY_DOUBLE_QUOTATION",
    NODE_STYLE_ATTR_VALUE_BODY_SINGLE_QUOTATION = "NODE_STYLE_ATTR_VALUE_BODY_SINGLE_QUOTATION",


    SCRIPT_BODY = "SCRIPT_BODY",

    STYLE_BODY = "STYLE_BODY",


    NODE_END_SCRIPT_1 = "NODE_END_SCRIPT_1",
    NODE_END_SCRIPT_2 = "NODE_END_SCRIPT_2",
    NODE_END_SCRIPT_3 = "NODE_END_SCRIPT_3",
    NODE_END_SCRIPT_4 = "NODE_END_SCRIPT_4",
    NODE_END_SCRIPT_5 = "NODE_END_SCRIPT_5",
    NODE_END_SCRIPT_6 = "NODE_END_SCRIPT_6",
    NODE_END_SCRIPT_7 = "NODE_END_SCRIPT_7",
    NODE_END_SCRIPT_8 = "NODE_END_SCRIPT_8",

    NODE_END_STYLE_1 = "NODE_END_STYLE_1",
    NODE_END_STYLE_2 = "NODE_END_STYLE_2",
    NODE_END_STYLE_3 = "NODE_END_STYLE_3",
    NODE_END_STYLE_4 = "NODE_END_STYLE_4",
    NODE_END_STYLE_5 = "NODE_END_STYLE_5",
    NODE_END_STYLE_6 = "NODE_END_STYLE_6",
    NODE_END_STYLE_7 = "NODE_END_STYLE_7",


    NODE_NAME = "NODE_NAME",
    NODE_BODY = "NODE_BODY",
    NODE_BODY_SELF_CLOSING = "NODE_BODY_SELF_CLOSING",

    NODE_ATTR_NAME = "NODE_ATTR_NAME",

    NODE_ATTR_VALUE_START = "NODE_ATTR_VALUE_START",
    NODE_ATTR_VALUE_BODY_DOUBLE_QUOTATION = "NODE_ATTR_VALUE_BODY_DOUBLE_QUOTATION",
    NODE_ATTR_VALUE_BODY_SINGLE_QUOTATION = "NODE_ATTR_VALUE_BODY_SINGLE_QUOTATION",
}